name: Generate Release Notes

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Generate Release Notes
      run: npm run release
      
    - name: Commit Release Notes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add release-notes.md
        git commit -m "Generate release notes for ${GITHUB_REF}"
        git push
